Version 0.5.0
ipfs/go-namesys pull request #31
Opened 2022-04-08 14:57 UTC by guseggert

This includes new OpenTelemetry dependencies and the addition of tracing spans.

2022-04-25 13:23 UTC, iand approved these changes

2022-04-26 14:54 UTC, BigLep commented
2022-04-26 conversation: need to bump version numbers and then will merge.

2022-04-26 17:54 UTC, lidel requested changes
@guseggert before you make a new release, mind reviewing and merging fix from https://github.com/ipfs/go-namesys/pull/32?

2022-04-27 20:44 UTC, lidel approved these changes
LGTM (rebased to include https://github.com/ipfs/go-namesys/pull/31).


@guseggert mind merging, so  we get a release that I can switch to in https://github.com/ipfs/go-ipfs/pull/8868?

2022-04-27 23:33 UTC, merged