feat: use peer.String() to produce a human-readable cache key
ipfs/go-namesys pull request #38
Opened 2023-02-22 15:27 UTC by laurentsenta

2023-02-22 16:22 UTC, lidel requested changes
lgtm, but we need to normalize key

2023-02-22 16:22 UTC, lidel commented on namesys.go
> +		cacheKey = ipnsKey.String()
This won't be enough because of legacy mess: `/ipns/id` can be Base58btc of peerid (`12...` which is not a valid CID), or CIDv1 with libp2p-key multihash in base36 (`k51..`). 

This screates surface for bugs, where someone tries to use CIDv1 base36 (`k..`) produced by `ipfs key list -l`  and it does not work because raw peerid `12...` is expected here.


I think we need something like:

```go
import ( 
  iface "github.com/ipfs/interface-go-ipfs-core"
...
		cacheKey = iface.FormatKeyID(ipnsKey)
```


This way the key will be canonical cidv1+libp2p-key+base36, the same user can see in `ipfs key list -l`

2023-02-23 10:02 UTC, laurentsenta commented on namesys.go
> +		cacheKey = ipnsKey.String()
Got it, thanks for the review and details.

I guess since all the cache keys go through the same calls, that's "just" a problem for the user that tries to use something other than a raw peer id in `IPFS_NS_MAP`.

I updated the PR so that we normalize all the keys loaded from `IPFS_NS_MAP` with the same `FormatKeyID`, and added tests!

2023-02-23 13:59 UTC, hacdias approved these changes

2023-03-08 17:27 UTC, lidel approved these changes
Thank you @laurentsenta.
Merging,  so we include this in future release.

2023-03-08 17:28 UTC, merged